// Copyright (c) 2026 Niobium Microsystems, Inc.
// SPDX-License-Identifier: Apache-2.0
//
// Part of a collaborative effort between Google, hardshell.ai and Niobium.
// Generated by Google HEIR; edit the model and regenerate rather than editing
// this file.

#include "openfhe.h"  // from @openfhe

using namespace lbcrypto;
using CiphertextT = Ciphertext<DCRTPoly>;
using ConstCiphertextT = ConstCiphertext<DCRTPoly>;
using CCParamsT = CCParams<CryptoContextCKKSRNS>;
using CryptoContextT = CryptoContext<DCRTPoly>;
using EvalKeyT = EvalKey<DCRTPoly>;
using PlaintextT = Plaintext;
using PrivateKeyT = PrivateKey<DCRTPoly>;
using PublicKeyT = PublicKey<DCRTPoly>;

std::vector<float> _assign_layout_16237132116865879658();
std::vector<float> _assign_layout_9721407330077517945();
std::vector<float> _assign_layout_6743199209520923868();
std::vector<float> _assign_layout_3792926423617899464();
std::vector<float> _assign_layout_5224897820953477293();
std::vector<float> _assign_layout_15429235295137564240();
struct run_inference__preprocessingStruct {
  std::vector<Plaintext> arg0;
  std::vector<Plaintext> arg1;
  std::vector<Plaintext> arg2;
  std::vector<Plaintext> arg3;
  std::vector<Plaintext> arg4;
  std::vector<Plaintext> arg5;
  std::vector<Plaintext> arg6;
  std::vector<Plaintext> arg7;
  std::vector<Plaintext> arg8;
  std::vector<Plaintext> arg9;
  std::vector<Plaintext> arg10;
  std::vector<Plaintext> arg11;
  std::vector<Plaintext> arg12;
  std::vector<Plaintext> arg13;
  std::vector<Plaintext> arg14;
  std::vector<Plaintext> arg15;
};
run_inference__preprocessingStruct run_inference__preprocessing(CryptoContextT cc);
std::vector<CiphertextT> run_inference__preprocessed(CryptoContextT cc, std::vector<CiphertextT> v0, std::vector<Plaintext> v1, std::vector<Plaintext> v2, std::vector<Plaintext> v3, std::vector<Plaintext> v4, std::vector<Plaintext> v5, std::vector<Plaintext> v6, std::vector<Plaintext> v7, std::vector<Plaintext> v8, std::vector<Plaintext> v9, std::vector<Plaintext> v10, std::vector<Plaintext> v11, std::vector<Plaintext> v12, std::vector<Plaintext> v13, std::vector<Plaintext> v14, std::vector<Plaintext> v15, std::vector<Plaintext> v16);
std::vector<CiphertextT> run_inference(CryptoContextT cc, std::vector<CiphertextT> v0);
std::vector<CiphertextT> run_inference__encrypt__arg0(CryptoContextT cc, std::vector<float> v0, PublicKeyT pk);
std::vector<float> run_inference__decrypt__result0(CryptoContextT cc, std::vector<CiphertextT> v0, PrivateKeyT sk);
CryptoContextT run_inference__generate_crypto_context();
CryptoContextT run_inference__configure_crypto_context(CryptoContextT cc, PrivateKeyT sk);
